# Site specific settings
title: "My Website"
# name: "Website name"
keywords: "Sumedh, Sumedh Yadav, homepage"
# baseurl: ""
baseurl : ""
url : ""
# url: "sumedhyadav.github.io/final_trial"
# url: "https://sumedhyadav.github.io/website_trial2/"
description: "This is my homepage. Blogs, hobbies, games, contact details..."
# cover: "/assets/img/cover.svg"
# fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
# ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: https-pages-themes-github-io-slate-another-page
# twitter: 
# facebook: 
# github: 
# google:

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: /:categories/:title/
